import web3 from './web3';

const address = '0xc2B50d75B07257D53fdf8F9f3968C96FCE5CB910';
const abi = [
	{
		"constant":true,
		"inputs":[{"name":"","type":"uint256"},{"name":"","type":"uint256"}],
		"name":"images",
		"outputs":[{"name":"","type":"string"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"constant":true,
		"inputs":[{"name":"i","type":"uint256"}],
		"name":"getphnobidders",
		"outputs":[{"name":"","type":"uint256[]"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"constant":false,
		"inputs":[{"name":"i","type":"uint256"},{"name":"_bidValue","type":"uint256"},{"name":"_phno","type":"uint256"}],
		"name":"bid",
		"outputs":[],
		"payable":false,
		"stateMutability":"nonpayable",
		"type":"function"
	},
	{
		"constant":true,
		"inputs":[{"name":"i","type":"uint256"}],"name":"getNoOfBids","outputs":[{"name":"","type":"uint256"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"constant":false,
		"inputs":[{"name":"_address","type":"address"}],
		"name":"inspectorAddRemove",
		"outputs":[],
		"payable":false,
		"stateMutability":"nonpayable",
		"type":"function"
	},
	{
		"constant":true,
		"inputs":[],
		"name":"owner",
		"outputs":[{"name":"","type":"address"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"constant":false,
		"inputs":[{"name":"i","type":"uint256"}],
		"name":"stopBid",
		"outputs":[],
		"payable":false,
		"stateMutability":"nonpayable",
		"type":"function"
	},
	{
		"constant":true,
		"inputs":[],
		"name":"getCarsLength",
		"outputs":[{"name":"","type":"uint256"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"constant":false,
		"inputs":[{"name":"i","type":"uint256"},{"name":"_basePrice","type":"uint256"},{"name":"_maxPrice","type":"uint256"},{"name":"_desc","type":"string"},{"name":"img1","type":"string"},{"name":"img2","type":"string"},{"name":"img3","type":"string"}],
		"name":"inspect",
		"outputs":[],
		"payable":false,
		"stateMutability":"nonpayable",
		"type":"function"
	},
	{
		"constant":true,
		"inputs":[{"name":"","type":"address"}],
		"name":"inspectors",
		"outputs":[{"name":"","type":"bool"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"constant":false,
		"inputs":[{"name":"_phno","type":"uint256"}],
		"name":"postAd",
		"outputs":[],
		"payable":false,
		"stateMutability":"nonpayable",
		"type":"function"
	},
	{
		"constant":true,
		"inputs":[{"name":"i","type":"uint256"}],
		"name":"getbids",
		"outputs":[{"name":"","type":"uint256[]"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"constant":true,
		"inputs":[{"name":"","type":"uint256"}],
		"name":"cars",
		"outputs":[{"name":"carid","type":"uint256"},{"name":"seller","type":"address"},{"name":"phno","type":"uint256"},{"name":"basePrice","type":"uint256"},{"name":"maxPrice","type":"uint256"},{"name":"inspected","type":"bool"},{"name":"stop","type":"bool"},{"name":"desc","type":"string"}],
		"payable":false,
		"stateMutability":"view",
		"type":"function"
	},
	{
		"inputs":[],
		"payable":false,
		"stateMutability":"nonpayable",
		"type":"constructor"
	}
];
export default new web3.eth.Contract(abi, address);